In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

pandas has 2 datastructure - 
1.Series - 1D Labeled array(single feature)
2.DataFrames - 2D labeled array(multiple features)
and these are the extension of nunmpy array(homogeneous data)

<!-- let us explore series -->

import pandas as pd

In [8]:
import pandas as pd
s = pd.Series([1,2,3,4,5])
print(s.dtype)
# there are many attributes for series, such as:
# - a shape
# - index
# - values
print(s.values)
print(s[4])

int64
[1 2 3 4 5]
5

In [7]:
i = ['a','b','c','d','e']
s.index = i
print(s['c'])

3

In [12]:
print(s.iloc[3])#Whenever we provide labels to a series, then we need to access the data by default indexes using the iloc function. 
print(s[3])
print(type(s))

4
4
<class 'pandas.core.series.Series'>

Now let us explore data frames, as they are the two-dimensional labeled arrays.

In [13]:
#dataframe
info={
    "name": ['a','b','c'],
    "age" :[12,13,14],
    "cgpa" :[9,9.2,9.3]
    
}
df = pd.DataFrame(info)
print(df,type(df))
print(df.index)#It will print the indices. 
print(df.columns)

  name  age  cgpa
0    a   12   9.0
1    b   13   9.2
2    c   14   9.3 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'cgpa'], dtype='object')

In [14]:
df

  name  age  cgpa
0    a   12   9.0
1    b   13   9.2
2    c   14   9.3

In [ ]:
We can create data frames in three ways:
1. Using dictionaries
2. Using the listed lists - these lists represent the entities where we have to assign the column names(columns = ['a','b','c']) Likewise
3. Using numpy arrays. Similar to the second one, there also they numpy will form a nested list of numbers, then we assign the column names
Three ways of creating data frames

In [15]:
import pandas as pd
import numpy as np

# 1. Creating a DataFrame using a Nested List
data_list = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'London'],
    ['Charlie', 35, 'Paris']
]
df_list = pd.DataFrame(data_list, columns=['Name', 'Age', 'City'])

print("DataFrame from Nested List:")
display(df_list)

# 2. Creating a DataFrame using a NumPy Array
data_array = np.array([
    [101, 'Electronics', 450],
    [102, 'Clothing', 300],
    [103, 'Home Decor', 150]
])
df_array = pd.DataFrame(data_array, columns=['ID', 'Category', 'Price'])

print("\nDataFrame from NumPy Array:")
display(df_array)

DataFrame from Nested List:

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

DataFrame from NumPy Array:

    ID     Category Price
0  101  Electronics   450
1  102     Clothing   300
2  103   Home Decor   150

We are saving this DataFrame to a CSV file. Here is the syntax:

In [16]:
import pandas as pd

# Data from the "Pandas with csv & json data" video
data = {
    'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Jack'],
    'Age': [25, 30, 35, 40, 22, 28, 33, 29, 31, 26],
    'Department': ['HR', 'IT', 'Marketing', 'IT', 'Finance', 'HR', 'IT', 'Marketing', 'IT', 'Finance'],
    'Salary': [50000, 60000, 70000, 65000, 55000, 52000, 62000, 71000, 64000, 56000]
}

df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)
print("File 'data.csv' has been created!")

File 'data.csv' has been created!

In [17]:
df = pd.read_csv("data.csv")
print(df,type(df))
# df = pd.read_json(employ.json)
#This is actually the way that we read the real-world data. Whatever the data might be, the format is CSV, JSON, Excel, or SQL. We use a method called `read_` that particular type:
- read_csv
- read_json
- read_excel
- read_sql
These are the methods. First, we read the data, convert the data into a data frame, and print the data.

   id     Name  Age Department  Salary
0   1    Alice   25         HR   50000
1   2      Bob   30         IT   60000
2   3  Charlie   35  Marketing   70000
3   4    David   40         IT   65000
4   5      Eve   22    Finance   55000
5   6    Frank   28         HR   52000
6   7    Grace   33         IT   62000
7   8    Heidi   29  Marketing   71000
8   9     Ivan   31         IT   64000
9  10     Jack   26    Finance   56000 <class 'pandas.core.frame.DataFrame'>

In [18]:
df

   id     Name  Age Department  Salary
0   1    Alice   25         HR   50000
1   2      Bob   30         IT   60000
2   3  Charlie   35  Marketing   70000
3   4    David   40         IT   65000
4   5      Eve   22    Finance   55000
5   6    Frank   28         HR   52000
6   7    Grace   33         IT   62000
7   8    Heidi   29  Marketing   71000
8   9     Ivan   31         IT   64000
9  10     Jack   26    Finance   56000

In [ ]:
We have different methods in pandas:
1. df.head() method in order to print the first 5 rows of the data.
2. df.tail() method in order to print the rows from the bottom of the data.
3. df.info() which describes the summary of the data set. It includes the column name, what kind of data it is holding, and the data type of data. 
df.describe() is a method which gives statistical information of numerical features. It includes count, mean, standard deviation, percentile, min, max, etc.
The df.nunique() will give you the number of unique values in the entire data set.
Df.Columns  is used to print the column names of the data set.
Df.shape is used to print the number of rows and columns. 
dF.sample() method is used to print random samples of required numbers.